/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cau3;

import javax.swing.JOptionPane;

public class Cau3 extends javax.swing.JFrame {

    /**
     * Creates new form Cau3
     */
    public Cau3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        LabelToolbar = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        FileBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        SaveAsbtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        Printbtn = new javax.swing.JButton();
        Sendbtn = new javax.swing.JButton();
        FBbtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        SearchBtn = new javax.swing.JButton();
        RaiseHandBtn = new javax.swing.JButton();
        ZoomBtn = new javax.swing.JButton();
        CursorBtn = new javax.swing.JButton();
        AdđFileBtn = new javax.swing.JButton();
        CameraBtn = new javax.swing.JButton();
        LockBtn = new javax.swing.JButton();
        PencilBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(144, 224, 239));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(173, 232, 244));

        jSeparator2.setForeground(new java.awt.Color(0, 119, 182));

        jPanel3.setBackground(new java.awt.Color(144, 224, 239));

        LabelToolbar.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        LabelToolbar.setText("Basic");

        ExitBtn.setBackground(new java.awt.Color(144, 224, 239));
        ExitBtn.setText("X");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(LabelToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(LabelToolbar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(ExitBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));

        jToolBar1.setBackground(new java.awt.Color(173, 232, 244));
        jToolBar1.setRollover(true);

        FileBtn.setBackground(new java.awt.Color(173, 232, 244));
        FileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons8-opened-folder-50.png"))); // NOI18N
        FileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(FileBtn);

        SaveBtn.setBackground(new java.awt.Color(173, 232, 244));
        SaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons8-save-50.png"))); // NOI18N
        SaveBtn.setFocusable(false);
        SaveBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SaveBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(SaveBtn);

        SaveAsbtn.setBackground(new java.awt.Color(173, 232, 244));
        SaveAsbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons8-save-as-50.png"))); // NOI18N
        SaveAsbtn.setFocusable(false);
        SaveAsbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SaveAsbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SaveAsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsbtnActionPerformed(evt);
            }
        });
        jToolBar1.add(SaveAsbtn);

        jSeparator1.setBackground(new java.awt.Color(0, 119, 182));
        jSeparator1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jSeparator1.setForeground(new java.awt.Color(0, 119, 182));
        jToolBar1.add(jSeparator1);

        Printbtn.setBackground(new java.awt.Color(173, 232, 244));
        Printbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons8-print-50.png"))); // NOI18N
        Printbtn.setFocusable(false);
        Printbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Printbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintbtnActionPerformed(evt);
            }
        });
        jToolBar1.add(Printbtn);

        Sendbtn.setBackground(new java.awt.Color(173, 232, 244));
        Sendbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons8-send-50.png"))); // NOI18N
        Sendbtn.setFocusable(false);
        Sendbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sendbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Sendbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendbtnActionPerformed(evt);
            }
        });
        jToolBar1.add(Sendbtn);

        FBbtn.setBackground(new java.awt.Color(173, 232, 244));
        FBbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons8-facebook-50.png"))); // NOI18N
        FBbtn.setFocusable(false);
        FBbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FBbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        FBbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FBbtnActionPerformed(evt);
            }
        });
        jToolBar1.add(FBbtn);

        jSeparator3.setBackground(new java.awt.Color(0, 119, 182));
        jSeparator3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jSeparator3.setForeground(new java.awt.Color(0, 119, 182));
        jToolBar1.add(jSeparator3);

        SearchBtn.setBackground(new java.awt.Color(173, 232, 244));
        SearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons8-search-48.png"))); // NOI18N
        SearchBtn.setFocusable(false);
        SearchBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SearchBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(SearchBtn);

        RaiseHandBtn.setBackground(new java.awt.Color(173, 232, 244));
        RaiseHandBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons8-hand-48.png"))); // NOI18N
        RaiseHandBtn.setFocusable(false);
        RaiseHandBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RaiseHandBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RaiseHandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaiseHandBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(RaiseHandBtn);

        ZoomBtn.setBackground(new java.awt.Color(173, 232, 244));
        ZoomBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons8-tablet-zoom-50.png"))); // NOI18N
        ZoomBtn.setFocusable(false);
        ZoomBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ZoomBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ZoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZoomBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(ZoomBtn);

        CursorBtn.setBackground(new java.awt.Color(173, 232, 244));
        CursorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons8-cursor-48.png"))); // NOI18N
        CursorBtn.setFocusable(false);
        CursorBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CursorBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CursorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursorBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(CursorBtn);

        AdđFileBtn.setBackground(new java.awt.Color(173, 232, 244));
        AdđFileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons8-add-file-48.png"))); // NOI18N
        AdđFileBtn.setFocusable(false);
        AdđFileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdđFileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AdđFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdđFileBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(AdđFileBtn);

        CameraBtn.setBackground(new java.awt.Color(173, 232, 244));
        CameraBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons8-vintage-camera-48.png"))); // NOI18N
        CameraBtn.setFocusable(false);
        CameraBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CameraBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CameraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CameraBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(CameraBtn);

        LockBtn.setBackground(new java.awt.Color(173, 232, 244));
        LockBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons8-delete-lock-50.jpg"))); // NOI18N
        LockBtn.setFocusable(false);
        LockBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LockBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        LockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LockBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(LockBtn);

        PencilBtn.setBackground(new java.awt.Color(173, 232, 244));
        PencilBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons8-pencil-50.png"))); // NOI18N
        PencilBtn.setFocusable(false);
        PencilBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PencilBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        PencilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PencilBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(PencilBtn);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Do you want to exit?", "Exit Form", JOptionPane.YES_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }// GEN-LAST:event_ExitBtnActionPerformed

    private void LockBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LockBtnActionPerformed
        // TODO add your handling code here:
        String[] options = new String[2];
        options[0] = "Lock";
        options[1] = "Unlock";
        int option = JOptionPane.showOptionDialog(this, "Do you want to lock or unlock file?", "Exit Form", 0,
                JOptionPane.INFORMATION_MESSAGE, null, options, null);
    }// GEN-LAST:event_LockBtnActionPerformed

    private void FileBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_FileBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Open file");
    }// GEN-LAST:event_FileBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Save file");
    }// GEN-LAST:event_SaveBtnActionPerformed

    private void SaveAsbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SaveAsbtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Save as file");
    }// GEN-LAST:event_SaveAsbtnActionPerformed

    private void PrintbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PrintbtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Print file");
    }// GEN-LAST:event_PrintbtnActionPerformed

    private void SendbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SendbtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Send file");
    }// GEN-LAST:event_SendbtnActionPerformed

    private void FBbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_FBbtnActionPerformed
        // TODO add your handling code here:
        // JOptionPane.showMessageDialog(this, "It's FaceBook time");
        JOptionPane.showMessageDialog(this, "Open FaceBook");
    }// GEN-LAST:event_FBbtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Search file");
    }// GEN-LAST:event_SearchBtnActionPerformed

    private void RaiseHandBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RaiseHandBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Sign In");
    }// GEN-LAST:event_RaiseHandBtnActionPerformed

    private void ZoomBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ZoomBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Zoom file");
    }// GEN-LAST:event_ZoomBtnActionPerformed

    private void CursorBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CursorBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Use cursor");
    }// GEN-LAST:event_CursorBtnActionPerformed

    private void AdđFileBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AdđFileBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Add new file");
    }// GEN-LAST:event_AdđFileBtnActionPerformed

    private void CameraBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CameraBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Screen Capture");
    }// GEN-LAST:event_CameraBtnActionPerformed

    private void PencilBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PencilBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Use pencil");
    }// GEN-LAST:event_PencilBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cau3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cau3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cau3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cau3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Cau3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdđFileBtn;
    private javax.swing.JButton CameraBtn;
    private javax.swing.JButton CursorBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton FBbtn;
    private javax.swing.JButton FileBtn;
    private javax.swing.JLabel LabelToolbar;
    private javax.swing.JButton LockBtn;
    private javax.swing.JButton PencilBtn;
    private javax.swing.JButton Printbtn;
    private javax.swing.JButton RaiseHandBtn;
    private javax.swing.JButton SaveAsbtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JButton Sendbtn;
    private javax.swing.JButton ZoomBtn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
